bandpass_filter_settings:
  bandpower_features:
    activity: true
    complexity: false
    mobility: false
  kalman_filter: false
  log_transform: true
  segment_lengths_ms:
    HFA: 100
    alpha: 500
    high beta: 333
    high gamma: 100
    low beta: 333
    low gamma: 100
    theta: 1000
bispectrum:
  bispectrum_features:
    mean: true
    sum: true
    var: true
  components:
    absolute: true
    imag: true
    phase: true
    real: true
  compute_features_for_whole_fband_range: true
  f1s:
    frequency_high_hz: 35.0
    frequency_low_hz: 5.0
  f2s:
    frequency_high_hz: 35.0
    frequency_low_hz: 5.0
  frequency_bands:
  - theta
  - alpha
  - low beta
  - high beta
burst_settings:
  burst_features:
    amplitude: true
    burst_rate_per_s: true
    duration: true
    in_burst: true
  frequency_bands:
  - low beta
  - high beta
  - low gamma
  threshold: 75.0
  time_duration_s: 30.0
coherence:
  channels: []
  features:
    max_allfbands: true
    max_fband: true
    mean_fband: true
  frequency_bands:
  - high beta
  method:
    coh: true
    icoh: true
feature_normalization_settings:
  clip: 3.0
  normalization_method: zscore
  normalization_time_s: 30.0
features:
  bandpass_filter: false
  bispectrum: false
  bursts: false
  coherence: false
  fft: false
  fooof: false
  linelength: false
  mne_connectivity: false
  nolds: false
  raw_hjorth: true
  return_raw: false
  sharpwave_analysis: false
  stft: false
  welch: false
fft_settings:
  features:
    max: false
    mean: true
    median: false
    std: false
  log_transform: true
  return_spectrum: false
  windowlength_ms: 1000
fooof:
  aperiodic:
    exponent: true
    knee: true
    offset: true
  freq_range_hz:
    frequency_high_hz: 40.0
    frequency_low_hz: 2.0
  knee: true
  max_n_peaks: 3
  min_peak_height: 0.0
  peak_threshold: 2.0
  peak_width_limits:
    frequency_high_hz: 12.0
    frequency_low_hz: 0.5
  periodic:
    band_width: false
    center_frequency: false
    height_over_ap: false
  windowlength_ms: 800.0
frequency_ranges_hz:
  HFA:
    frequency_high_hz: 400.0
    frequency_low_hz: 200.0
  alpha:
    frequency_high_hz: 12.0
    frequency_low_hz: 8.0
  high beta:
    frequency_high_hz: 35.0
    frequency_low_hz: 20.0
  high gamma:
    frequency_high_hz: 200.0
    frequency_low_hz: 90.0
  low beta:
    frequency_high_hz: 20.0
    frequency_low_hz: 13.0
  low gamma:
    frequency_high_hz: 80.0
    frequency_low_hz: 60.0
  theta:
    frequency_high_hz: 8.0
    frequency_low_hz: 4.0
kalman_filter_settings:
  Tp: 0.1
  frequency_bands:
  - theta
  - alpha
  - low beta
  - high beta
  - low gamma
  - high gamma
  - HFA
  sigma_v: 1.0
  sigma_w: 0.7
mne_connectivity:
  method: plv
  mode: multitaper
mne_connectiviy:
  method: plv
  mode: multitaper
nolds_features:
  correlation_dimension: false
  data:
    frequency_bands:
    - low beta
    raw: true
  detrended_fluctutaion_analysis: false
  features:
    correlation_dimension: false
    detrended_fluctuation_analysis: false
    hurst_exponent: false
    lyapunov_exponent: true
    sample_entropy: false
  frequency_bands:
  - low beta
  hurst_exponent: false
  lyapunov_exponent: true
  raw: true
  sample_entropy: false
postprocessing:
  feature_normalization: true
  project_cortex: false
  project_subcortex: false
preprocessing:
- raw_resampling
- notch_filter
- re_referencing
preprocessing_filter:
  bandpass_filter: true
  bandpass_filter_settings:
    frequency_high_hz: 200.0
    frequency_low_hz: 3.0
  bandstop_filter: true
  bandstop_filter_settings:
    frequency_high_hz: 160.0
    frequency_low_hz: 100.0
  highpass_filter: true
  highpass_filter_cutoff_hz: 3.0
  lowpass_filter: true
  lowpass_filter_cutoff_hz: 200.0
project_cortex_settings:
  max_dist_mm: 20.0
project_subcortex_settings:
  max_dist_mm: 5.0
raw_normalization_settings:
  clip: 3.0
  normalization_method: zscore
  normalization_time_s: 30.0
raw_resampling_settings:
  resample_freq_hz: 1000.0
sampling_rate_features_hz: 200.0
segment_length_features_ms: 333.0
sharpwave_analysis_settings:
  apply_estimator_between_peaks_and_troughs: true
  detect_peaks:
    distance_peaks_ms: 10.0
    distance_troughs_ms: 5.0
    estimate: true
  detect_troughs:
    distance_peaks_ms: 5.0
    distance_troughs_ms: 10.0
    estimate: true
  estimator:
    max:
    - prominence
    - sharpness
    mean:
    - interval
    median: []
    min: []
    var: []
  filter_ranges_hz:
  - frequency_high_hz: 80.0
    frequency_low_hz: 5.0
  - frequency_high_hz: 30.0
    frequency_low_hz: 5.0
  sharpwave_features:
    decay_steepness: false
    decay_time: false
    interval: true
    peak_left: false
    peak_right: false
    prominence: true
    rise_steepness: false
    rise_time: false
    sharpness: true
    slope_ratio: false
    trough: false
    width: false
stft_settings:
  features:
    max: false
    mean: true
    median: false
    std: false
  log_transform: true
  return_spectrum: false
  windowlength_ms: 500
welch_settings:
  features:
    max: false
    mean: true
    median: false
    std: false
  log_transform: true
  return_spectrum: false
  windowlength_ms: 1000
