import time

import numpy as np
import pandas as pd

import realtime_normalization
import rereference


def run(gen, features, settings, df_m1):
    """Run real-time analysis of neurophysiological data generated by "gen".

    Parameters
    ----------
    gen : generator object
        generator that yields segments of data.
    features: 
        Feature_df object (needs to be initialized beforehand)
    settings : dict
        dictionary of settings such as "seglengths" or "frequencyranges"
    df_m1 : data frame
        data frame with the channel configurations and rereferencing settings.

    Returns
    -------
    features : data frame
        features defined as in settings in shape [M, N] where N is the
        time index and M is the number of features
    """

    if settings["methods"]["re_referencing"] is True:
        ch_names = pd.Series.tolist(df_m1['name'])
        refs = pd.Series.tolist(df_m1['rereference'])
        subcortex_idx = df_m1[(df_m1["used"] == 1) & (df_m1["target"] == 0)
                              & (df_m1["ECOG"] == 0)].index
        cortex_idx = df_m1[(df_m1["used"] == 1) & (df_m1["target"] == 0)
                           & (df_m1["ECOG"] == 1)].index
        rest_idx = df_m1[(df_m1["used"] == 0) | (df_m1["target"] == 1)].index

    fs_new = int(settings["resampling_rate"])
    normalize_time = \
        int(settings["normalization_settings"]["normalization_time"])
    offset = \
        int(1000 * settings["bandpass_filter_settings"]["segment_lengths"][0])
    cnt_samples = 0

    if settings["methods"]["normalization"] is True:
        # raw signal is normalized
        normalize_samples = int(normalize_time * features.fs)
        feature_arr = pd.DataFrame()
    
    while True:
        ieeg_batch = next(gen, None)
        start_time = time.time()
        if ieeg_batch is None:
            return feature_arr

        # call rereference
        if settings["methods"]["re_referencing"] is True:
            ieeg_batch = \
                rereference.rereference(ieeg_batch, ch_names, refs, rest_idx,
                                        cortex_idx, subcortex_idx,
                                        split_data=False)

        # now normalize raw data 
        if settings["methods"]["normalization"] is True:
            if cnt_samples == 0:
                raw_arr = ieeg_batch
            else:
                raw_arr = np.concatenate((raw_arr, ieeg_batch), axis=1)
            
            raw_norm = \
                realtime_normalization.realtime_normalization(
                    raw_arr, cnt_samples, normalize_samples, features.fs,
                    settings["normalization_settings"]["normalization_method"])

            # calculate features
            feature_series = features.estimate_features(raw_norm) 
        else: 
            feature_series = features.estimate_features(ieeg_batch)
        
        if cnt_samples == 0:
            cnt_samples += int(features.fs)
            feature_series["time"] = offset  # ms
            feature_arr = pd.DataFrame([feature_series])
            
        else:
            cnt_samples += int(features.fs / fs_new)
            feature_series["time"] = cnt_samples*1000/features.fs  # ms
            feature_arr = feature_arr.append(feature_series, ignore_index=True)
        print(f"{str(np.round(cnt_samples / 1000,2))} seconds of "
              "data processed.")
        print("took: "+str(round(time.time() - start_time, 2))+" seconds")
